---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: loki
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAWRWV3VsvQcaiAmuRDUuDlvcXIJnwZzIgYm9tHEYYdmiQUCN13lwGiWkGGoFwaAUAY6gCBsq4ZgQJENvPXcJKGqhKlTMdf//eY1H0KNEPg3xkSOBNgWR/eFLi/SLquGlTk6qVVAQRY2Wm0WFGlZy1pdk2NuArQw+oZ6Dwi6J2WqTZX5EoBv5LVcttRkE8YKMuVfLZVbaFnnb0msKZ/EJaXel/HRanqAsVq28pvlyRfOAjKWITRcw+pEv+gwRUaLSs8Qkl6I9EdjZ1tPbmI9hL+ydxboEsUN9kWLzpoSU79b8mXrgWan2L47i0N/BUAFNlu2o7UT7evMn7UnZgqK8phd/5IGqLIC8UCr5pVIhyOGpTqZQqqPeBBAtPqHpfVgAmWH7CfEDVE9G8BRa7eCM2cjaS5mZVZHGG1dpRJb92xPIETsSVT86/4LEgJ6x51Ez+QQo/Qzpl905vu95J7nxSGV2oqhloX0dTkIxu2lyjeVwkQ6yH8r20SVuE29FZg7ZlVzIbubnmcVQ68MqTngqIM7/sT24CyQFOi0cs/YnLjBY8usJ8x5k41hESMBLe/0UsaXneTGVgAk315SKCC1bpNH9PxSssXsfnL/L1rojkaRF55d6N1sjYOODdlL/Am22TaUdKbgaOZwOZ0zcOmrHAeVfpgpWU3d5VDR/GB0BdCUstmeQ5fd5IJgBLpcuTGpN5NmWMF7J4oRct9jhHn6bNB/TbaiQ==
    SECRET_ACCESS_KEY: AgCaNFFu7plB6fYdZ0l8EsEcn4yUk48FIeDL1bOb6htNevbdHVUMBNYNS5A/G4fl/ZdOBEjAKtoPiI5NeZLGtr9Fe3V95/Se5FZMSfISkxPQveiOdUEhDCS2EPwSOrYr7WlVahWYiBOeJcPjTcqnJC/AIsB3163Z3oqmgmMXU+NbVKlJDYRTctcKS7cc8wTUCI+eF8lxQu54uk6vkreF7zUGfWarAUO38yHwptfaE40ac7mwY3wsaKjMBMpQM2OtV0N6K5hUGwg/OuF6BznDsF9wtAr76FFdcBUavjkg/Hsc5ArRdTGAx1CntHWNoOKDctZlDectMMgeWMa1/H/BB2QF2Cs/JeI0kycyZziruAIvKuhqrdfe6SXSbvq7XkiYjlXQsquUq2WD4HBXml7edRNOfhm8SSBbOJbmkk5xw+tw8wPD04NtyIbyj6gSEF8K6PEJscimqlOPhpqLGsxyp5HUxkqQb4CVPulAvVEPZ9rVGG04L1t+jvhSY2cyk9k7fvJgZZdJbQEp9UXSxBvO/SIxSXHw/OEvrG36AbYA033AsjiVCX4lmwene3RfG/KwcFA7K6/zj3Vs8XNjQVJFCCMcHhANr+dffMqHfoijxM/CrsbIHzY0cRPXL+nXs1r81QFTBQfGTQqMDS3Q5sWhJbqnufGljGcrxvC7GriWRtsOHZ3N0CPvVT+uzm7/Jg4qFYt6R5MKbZ6JU9OkidTT1AL7wspHX3gYhmAJLKLxG/I3YQeniyWVwNUi #pragma: allowlist secret
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: loki
    type: Opaque
