---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: org.democratic-csi.iscsi
    volume.kubernetes.io/storage-provisioner: org.democratic-csi.iscsi
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: immich
  name: immich
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: truenas-iscsi-csi
  volumeMode: Filesystem
