---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich
spec:
  secretName: immich-tls #pragma: allowlist secret
  dnsNames:
    - 'immich.cloudydad.world'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
