---
roles:
  - name: artis3n.tailscale
collections:
  - name: ansible.utils
  - name: community.general
    version: ">=12.0.0"
  - name: ansible.posix
  - name: kubernetes.core
    version: ">=6.0.0"
