---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik
spec:
  secretName: authentik-tls #pragma: allowlist secret
  dnsNames:
    - 'authentik.cloudydad.world'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
