---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oncall
spec:
  secretName: oncall-tls #pragma: allowlist secret
  dnsNames:
    - 'oncall.cloudydad.world'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
