---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oncall
spec:
  chart:
    spec:
      chart: oncall
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: '>=1.12.1-0'
  interval: 50m
  releaseName: oncall
  targetNamespace: oncall
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: oncall-values
