---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
spec:
  chart:
    spec:
      chart: coredns
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: flux-system
      version: '>=1.36.1-0'
  interval: 30m
  releaseName: coredns
  targetNamespace: kube-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: coredns-values
