---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage
spec:
  secretName: homepage-tls #pragma: allowlist secret
  dnsNames:
    - 'homepage.cloudydad.world'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
