---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
spec:
  chart:
    spec:
      chart: valkey
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
      version: "3.0.31"
  interval: 30m
  releaseName: valkey
  targetNamespace: valkey
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: valkey-values
