apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vm-logs
spec:
  secretName: vm-logs-tls
  dnsNames:
    - 'vmlogs.cloudydad.world'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
