---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudydad
spec:
  secretName: cloudydad-wildcard-tls #pragma: allowlist secret
  dnsNames:
    - '*.cloudydad.world'
    - '*.cloudydad.life'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
