---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: letsencrypt.disarm220@passmail.net
    privateKeySecretRef:
      name: letsencrypt-dns01-private-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
        selector:
          dnsNames:
            - '*.cloudydad.life'
            - '*.cloudydad.world'
            - 'alertmanager.cloudydad.world'
            - 'authentik.cloudydad.world'
            - 'cloudydad.life'
            - 'cloudydad.world'
            - 'goldilocks.cloudydad.world'
            - 'grafana.cloudydad.world'
            - 'immich.cloudydad.world'
            - 'karakeep.cloudydad.world'
            - 'ntfy.cloudydad.world'
            - 'ollama.cloudydad.world'
            - 'podinfo.cloudydad.world'
            - 'rsshub.cloudydad.world'
            - 'signoz.cloudydad.world'
            - 'uptime-kuma.cloudydad.world'
            - 'vmagent.cloudydad.world'
            - 'vmalert.cloudydad.world'
            - 'vmlogs.cloudydad.world'
            - 'vmmetrics.cloudydad.world'
            - 'wakapi.cloudydad.world'
            - 'whoami.cloudydad.world'
