---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCnd5/HwN6+tMUQNtEgrE+HKqKElzpFJlDQobtxg1yW0eAcK14IvnmGy5pO3q7k6buMhhOtArnhNvPasOUXlQSJVVA4iTALKN6w67WVfgKs/kVG8e3Kf9ubywTjuCLpslRQCIyyHZrdTvalZKO5qSf9cSwktHbPNJyM8iKAK5OF2NGsBIfNpDK2AMUa93ntoCvR6PYZMfmEiDpdIOT0d30fBo3sPNFPPGksw0BtHjd9E6Ij6nzZp35rbyHmTAgTQEgUtQWST1/5CB8zDirXBDIaoant3KDnP0OXvqNBVkKPr2PHBVdQU4P0LF6j35iomS45mfqKDfSuVaNipao0wFZHuuzb4tCHT2VIdag5TSEKnDs9BxJev2u8gsrDVh1Mfy32Om/To83OYbbcC2o+lGXvllZiksT3KuwJE6CnvlfX0lDvJp5qkjIGxjrEpR0qe76XdAW+RaP86GHzGZU8KScKJZE48a5JRndRy5S3EYm4SisxDm3nys5bemN73HE4uQJ/+EMrQuyqElXJBKLzDYZO1h5n4LCeKhx0T2AoqSQez00WAHFp/5aFlgU6LMvO/26TGs4gD8szEfdXVSSAV+l1JtVxdK8NZf1CjNiIvrKFCtenOTpvnNQzWPKK5QGimp/ZbyK4v2OsoGwg/WJFbZmAxlLXxBGxV61+4lJ/elb870yKSh7t9vsDSUN9iw27ppriQanfp5v/dheLVmgAY8WL2/T2CqxJ3/Z/KJKqD26BeCwSETlWfX3h
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
