---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAEZymQU/uIpODLofXnNUM3qR/0SQpKYKUoWMy9qy/AIJPS7EqldrdcrUlJLDIOozNYGc/K5NEzQdMdW2Uf1AN9CyRlxyDUY3k+SliaztuRpPdkyGYH8xS825qi5aBvJ4r2069Gkn5TknAwyfcxirsNjb92Aj/cbps9Y0iDSagRTYy5yChK3KijH6vzzQ7NyyCRvDi8hTX1zLOxlf/pWa9ngO14b2Syen8VP+qTPWBhDC3ctJ+dGg2Twao+KwBwBjuv/2amVmBFVYs/bhH3sUHsUJb5X14d2VytP6rLp8t8tZaWFOa1tqWUVNHo2O4M4iVzhOfNKOS0VuzXBEUSNAGV7EeRpu9we5b9LSppH7b+ogaeBSymdJ1+nTiew/n13ssuLmmebo2xP8x7H1e8R1szyRBUIzaVAmodYd1wD772RlCYXli+uzHMKhlFa0n6+eSI0HCELXCSel6jRUf6V+OzIof8FP/DoTvGif2oFZO1xa786tRmh/zN6Ian8sapRQDaPiAxG4xICgid/7MDQS6kQGuwP96qLNR0eiIS5tkbryzNwt1waZxycU4Seblr7UPFL3Z8Y7L2je2RaTxjU2rhAvfXd/x9sryD9YoxiRy7eLK4C3CCiCIGx0n0rdFqKsaZaLLm5ZKX92RELxU1FiTiUwSMED3yqxQhxE4tpCofssW6uWtQ0cW5xj7VydKxjCZ0r+VFtwaD7HJZtNC3xG1xuFSudMj42YDz4p+xVyAAy2/3eYvpco9W #pragma: allowlist secret
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
