apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: goldilocks
spec:
  secretName: goldilocks-tls
  dnsNames:
    - 'goldilocks.cloudydad.world'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
