---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldilocks
spec:
  chart:
    spec:
      chart: goldilocks
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
      version: '>=9.0.1'
  interval: 50m
  releaseName: goldilocks
  targetNamespace: goldilocks
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: goldilocks-values
