---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz
spec:
  chart:
    spec:
      chart: signoz
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: flux-system
      version: '0.70.0'
  interval: 50m
  releaseName: signoz
  targetNamespace: signoz
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: signoz-values
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz-k8s-infra
spec:
  chart:
    spec:
      chart: k8s-infra
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: flux-system
      version: '0.12.1'
  interval: 50m
  releaseName: signoz-k8s-infra
  targetNamespace: signoz
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: signoz-k8s-infra-values
