---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: signoz
    meta.helm.sh/release-namespace: signoz
    volume.beta.kubernetes.io/storage-provisioner: org.democratic-csi.iscsi
    volume.kubernetes.io/storage-provisioner: org.democratic-csi.iscsi
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/version: 24.1.2
    clickhouse.altinity.com/app: chop
    clickhouse.altinity.com/chi: signoz-clickhouse
    clickhouse.altinity.com/cluster: cluster
    clickhouse.altinity.com/namespace: signoz
    clickhouse.altinity.com/reclaimPolicy: Retain
    clickhouse.altinity.com/replica: "0"
    clickhouse.altinity.com/shard: "0"
    helm.sh/chart: clickhouse-24.1.15
    helm.toolkit.fluxcd.io/name: signoz
    helm.toolkit.fluxcd.io/namespace: signoz
  name: data-clickhouse-cluster-0
  namespace: signoz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: truenas-iscsi-csi
  volumeMode: Filesystem
