apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: podinfo
  namespace: podinfo
spec:
  secretName: podinfo-tls
  dnsNames:
    - 'podinfo.cloudydad.world'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
