---
- name: Create manifests directory on first control plane node
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: "0644"
  when: ansible_hostname == hostvars[groups[group_name_control_plane | default('controlplane')][0]]['ansible_hostname']

- name: Download vip cloud provider manifest to first control plane node
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/{{ kube_vip_cloud_provider_tag_version | default('main') }}/manifest/kube-vip-cloud-controller.yaml" # noqa yaml[line-length]
    dest: "/var/lib/rancher/k3s/server/manifests/kube-vip-cloud-controller.yaml"
    owner: root
    group: root
    mode: "0644"
  when: ansible_hostname == hostvars[groups[group_name_control_plane | default('controlplane')][0]]['ansible_hostname']

- name: Copy kubevip configMap manifest to first control plane node
  template:
    src: "kubevip.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/kubevip.yaml"
    owner: root
    group: root
    mode: "0644"
  when: ansible_hostname == hostvars[groups[group_name_control_plane | default('controlplane')][0]]['ansible_hostname']
