---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nix-dev-config
  namespace: nix-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi-csi
  resources:
    requests:
      storage: 3Gi
