---
- name: Configure Groups
  ansible.builtin.group:
    name: '{{ item.name }}'
    gid: '{{ item.gid }}'
    state: '{{ item.state }}'
    system: '{{ item.system }}'
  when: ansible_groups is defined
  loop: '{{ ansible_groups }}'
  loop_control:
    label: '{{ item.name }}'
  tags:
    - create-users
    - create-groups

- name: Configure Users
  ansible.builtin.user:
    name: '{{ item.name }}'
    comment: '{{ item.comment | default(omit) }}'
    password: '{{ item.password | default(omit) }}'
    group: '{{ item.group | default(omit) }}'
    groups: '{{ item.groups | default(omit) }}'
    home: '{{ item.home | default(omit) }}'
    create_home: '{{ item.create_home | default(omit) }}'
    remove: '{{ item.remove | default(omit) }}'
    expires: '{{ item.expires | default(omit) }}'
    shell: '{{ item.shell | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    system: '{{ item.system | default(omit) }}'
    uid: '{{ item.uid | default(omit) }}'
  when: ansible_users is defined
  loop: '{{ ansible_users }}'
  loop_control:
    label: '{{ item.name }}'
  tags:
    - create-users
  ignore_errors: '{{ ansible_check_mode }}'

- name: Add SSH Keys for Users
  ansible.posix.authorized_key:
    user: '{{ item.name }}'
    comment: '{{ item.authkey_comment | default(omit) }}'
    exclusive: '{{ item.authkey_exclusive | default(omit) }}'
    key: 'https://github.com/{{ item.authkey_gh_username }}.keys'
    manage_dir: '{{ item.authkey_manage_dir | default(omit) }}'
    state: '{{ item.authkey_state | default(omit) }}'
  when: ansible_users is defined and item.state != "absent"
  loop: '{{ ansible_users }}'
  loop_control:
    label: '{{ item.name }}'
  ignore_errors: '{{ ansible_check_mode }}'
  tags:
    - create-users
    - update-sshkeys

- name: Set NOPASSWD for Sudoers
  ansible.builtin.lineinfile:
    state: present
    path: /etc/sudoers.d/90-cloud-init-users
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD:ALL' # pragma: allowlist secret
    validate: 'visudo -cf %s'
  notify: Reload sudoers

- name: Configure motd for Ubuntu Systems
  when: ansible_distribution == "Ubuntu"
  block:
    - name: Cleanup update-motd.d directory
      file:
        path: /etc/update-motd.d
        state: absent

    - name: Create update-motd.d directory
      file:
        path: /etc/update-motd.d
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Copy over motd files
      ansible.builtin.copy:
        src: 'files/etc/update-motd.d/{{ item }}'
        dest: '/etc/update-motd.d/{{ item }}'
        owner: root
        group: root
        mode: 0755
      loop:
        - 00-header
        - 90-updates-available
        - 91-release-upgrade
        - 92-unattended-upgrades
        - 95-hwe-eol
        - 97-overlayroot
        - 98-fsck-at-reboot
        - 98-reboot-required

    - name: Copy over legal file
      ansible.builtin.copy:
        src: 'files/etc/legal'
        dest: '/etc/legal'
        owner: root
        group: root
        mode: 0644
