---
apiVersion: v1
data:
  KARAKEEP_VERSION: release
  NEXTAUTH_URL: http://localhost:3000
  CRAWLER_FULL_PAGE_ARCHIVE: "true"
  DB_WAL_MODE: "true"
  MAX_ASSET_SIZE_MB: "200"
  CRAWLER_VIDEO_DOWNLOAD: "true"
  DISABLE_SIGNUPS: "true"
  OPENAI_BASE_URL: https://opencode.ai/zen/v1
  INFERENCE_TEXT_MODEL: big-pickle
  # INFERENCE_IMAGE_MODEL: big-pickle
  EMBEDDING_TEXT_MODEL: big-pickle
  INFERENCE_JOB_TIMEOUT_SEC: "600"
  INFERENCE_FETCH_TIMEOUT_SEC: "600"
kind: ConfigMap
metadata:
  name: karakeep-configuration
