---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea
spec:
  secretName: gitea-tls
  dnsNames:
    - 'git.cloudydad.world'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
