---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: invidious
spec:
  chart:
    spec:
      chart: invidious
      sourceRef:
        kind: HelmRepository
        name: invidious
        namespace: flux-system
      version: '2.1.0'
  interval: 30m
  releaseName: invidious
  targetNamespace: invidious
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: invidious-values
    - kind: Secret
      name: invidious-secret-values
