---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-iscsi
  namespace: storage
spec:
  chart:
    spec:
      chart: democratic-csi
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
      version: '>=0.14.6-0'
  interval: 1h0m0s
  releaseName: democratic-csi-iscsi
  targetNamespace: storage
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: democratic-csi-iscsi-values
    - kind: Secret
      name: democratic-csi-secret-values
