---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: storage
spec:
  chart:
    spec:
      chart: snapshot-controller
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
      version: '>=0.2.4-0'
  interval: 1h0m0s
  releaseName: snapshot-controller
  targetNamespace: storage
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: snapshot-controller-values
