---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - rbac.yaml
  - cronjob.yaml
  - sealed-gitea-archive-token.yaml
configMapGenerator:
  - name: github-archiver-script
    files:
      - archiver.py
    options:
      disableNameSuffixHash: true
