---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-archive-token
  namespace: gitea
spec:
  encryptedData:
    gitea_token: AgAlq/T6eCKeLBJ6o3nRscrieMLmbggZ2l5pry0xBSqUvTim+HyUOKAAH1E+UHOfwLNPIeEae4GvjxrGTjzhOPydwuDLK/kMBk/jqznVWejDqEM+fLzdl28oo/+5zDBkUJYWbfnMaJl+deWn45a+u55VODdZG5gJgC32IlFOZSUfrUu9d4uNcDIAUtRVjKpzvyFCkSVea8fMvSvRHhPA6dLHoNo7W2/kOYVkzGWv3KIJZQgnng1g00ek0d7xXT4DTa3vKZNeyi6jUaeK60qX4SPvJWBozX/IS6/x5WJsi6D36my1bDwSHRHzCVJVLTJfxEF+41bCUoCzDkct7b9bFE66xmn8NW5gkpBN+okgsT5xetkh+QzZU+uYmdKyXW3NIPRGFLMn+LH+pyztl7XicpPnE+PIVJmxB+TRCNmGNP1BjcBtKNHz/REuc8VAPuNNFjHbp9XZbe3vtcPApofnYu0BBiqBp6SntRZ2QCkjBt74xnaskUoe+NLbfLAkUm+YsDJUF+SsDJA/xiTw05N/l+Xnf6C88Evx8n01EVo31wj5rJNMwYhbXupRhQIELuuSJSVwQ3o7Okotkaxpat7mUZKHAqTbwc3UI9nx57l5w0Aq+WLftOJo2PFDHe5TICknuxAienTfKZRPd3+wfVpJiILD9E6sTeCypXgK2gM5n0GeGrEcujc/53WRgnt6yeDavCgKNE1b7WGOQ9DWJ/nh6xnaUICn8Yg4f4e+xfUJ++KNHmoTVKuvzmKT
    github_token: AgAoQkPIa0CMHpDMFvJR4ilfKSQzN5eD38E61eYVTuWnAcWe5PSbAKP1oqvzlrK/tqGiGvFOnj+ILqaCcN5TzwtmeVPAOVbNHLVmTvudn+RceHl3neHa5V2qAJMgf8GSfc+Cg4V7R9veqPgbEpPNK33clXROATB+e5OPrCFZ1M+fFvoKC1WsIwYqLyxQzbvPT1EG5pqqSEsjZnrykfaTUf7IyKlQKstLdEzUgTgKzDwFSN/0uTkQNSDkxyTtwxAaIDnN9sE0GHql4Iekrmw5Aq7xGUwY+QnmbyK4X+opYEMdfXmABVNmVryLQ7hKvNtbrrwLpHyprYDTFV23OgCWpxE2xyCd0JglwQ+mYMQLTwQ+xW21Tbne41BLEtIcdWfv15GwIHad+PVGFEMSPIjUkhuOIJtSbSZjDA2xKxUQuXSmFpF1aAVwWL+NSAGi0qSo4B1TOuSv35qqVA03yO7a28QpzHOsfkdGzwKbBdRAiizsjIWCt4mq+2ahDGdeFLTnx1wDsxqil0zhCWrZI0NdRsRLDfeNQJgbcp/hnJ6GSEnOgldoCoAMsIJg+x0kf8MuNbWVs1/FPRtVk7Ojh9m2mQdnlJ/4uqVkFw4r9irCsCXTANrF8glyK1uPzZLUlAG7E27rjWTWkiXO/FuJiHNmhAohyi8VP2TjkcpwZRBoAthcNxufPNbLewDe6VRmlasKrikpz+Xc6/wPAg2vHkE1z8B93wNzBcXFCeRu1hNqvV3UirOtbGFcRAhZ
  template:
    metadata:
      name: gitea-archive-token
      namespace: gitea
    type: Opaque
