---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rsshub
spec:
  chart:
    spec:
      chart: rsshub
      sourceRef:
        kind: HelmRepository
        name: rssnext
        namespace: flux-system
      version: '0.1.4'
  interval: 30m
  releaseName: rsshub
  targetNamespace: rsshub
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: rsshub-values
