---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ntfy
spec:
  secretName: ntfy-tls #pragma: allowlist secret
  dnsNames:
    - 'ntfy.cloudydad.world'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
