apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami
spec:
  secretName: whoami-tls
  dnsNames:
    - 'whoami.cloudydad.world'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
