---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cloudydad-data-center
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/wrightbradley/cloudydad-data-center.git
  ref:
    branch: main
  secretRef:
    name: flux-system
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/cluster
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/cloudydad
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: cloudydad-data-center
