---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustdesk-data-pvc
spec:
  storageClassName: truenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
