---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n
spec:
  secretName: n8n-tls #pragma: allowlist secret
  dnsNames:
    - 'n8n.cloudydad.world'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
