---
apiVersion: 'cilium.io/v2alpha1'
kind: CiliumBGPPeeringPolicy
metadata:
  name: 01-bgp-peering-policy
spec:
  virtualRouters:
    - localASN: 64513
      # serviceSelector:
      #   matchExpressions:
      #     - { key: somekey, operator: NotIn, values: ['never-used-value'] }
      podIPPoolSelector:
        matchLabels:
          app.cilium.io/advertise-bgp: 'true'
      exportPodCIDR: false
      neighbors:
        - peerAddress: '172.18.1.1/32'
          peerASN: 64512
          # authSecretRef: secretname
          eBGPMultihopTTL: 10
          connectRetryTimeSeconds: 120
          holdTimeSeconds: 90
          keepAliveTimeSeconds: 30
          gracefulRestart:
            enabled: true
            restartTimeSeconds: 120
