---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: 01-bgp-cluster-config
spec:
  bgpInstances:
    - name: 'cloudydad'
      localASN: 64522
      peers:
        - name: 'opnsense'
          peerASN: 64512
          peerAddress: '172.18.1.1'
          peerConfigRef:
            name: '01-bgp-peer-config'
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: 01-bgp-peer-config
spec:
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  # authSecretRef: bgp-auth-secret
  ebgpMultihop: 10
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 120
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: 'bgp'
---
# apiVersion: cilium.io/v2alpha1
# kind: CiliumBGPAdvertisement
# metadata:
#   name: bgp-advertisements
#   labels:
#     advertise: bgp
# spec:
#   advertisements:
#     - advertisementType: 'PodCIDR'
#       attributes:
#         communities:
#           standard: ['64512:99']
#         localPreference: 99
#     - advertisementType: 'Service'
#       service:
#         addresses:
#           - ClusterIP
#           - ExternalIP
#           - LoadBalancerIP
#       selector:
#         matchExpressions:
#           - { key: app.kubernetes.io/name, operator: In, values: [traefik] }
#       attributes:
#         communities:
#           standard: ['64512:100']
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: 01-bgp-advertisement
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: 'Service'
      service:
        addresses:
          - ClusterIP
          - ExternalIP
          - LoadBalancerIP
      selector: # <-- select all services
        matchExpressions:
          - { key: somekey, operator: NotIn, values: ['never-used-value'] }
