---
- name: Reset Kubernetes cluster
  hosts: kubernetes
  gather_facts: true
  roles:
    - role: reset
      become: true
    - role: raspberrypi
      become: true
      vars: {state: absent}
  post_tasks:
    - name: Reboot and wait for node to come back up
      become: true
      reboot:
        reboot_command: "{{ custom_reboot_command | default(omit) }}"
        reboot_timeout: 3600
