---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik/kustomization.yaml
  - ./database/kustomization.yaml
  - ./network/kustomization.yaml
  - ./sealed-secrets/kustomization.yaml
  - ./storage/kustomization.yaml
  - ./system-upgrade-controller/kustomization.yaml
